//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiUpload.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikiUpload.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki-Up.
        /// </summary>
        public static string AboutApplicationNameText {
            get {
                return ResourceManager.GetString("AboutApplicationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string AboutMenuItemText {
            get {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Wiki-Up.
        /// </summary>
        public static string AboutTitleText {
            get {
                return ResourceManager.GetString("AboutTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watch list.
        /// </summary>
        public static string AddToWatchlistLabelText {
            get {
                return ResourceManager.GetString("AddToWatchlistLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the uploaded files to your watch list..
        /// </summary>
        public static string AddToWatchlistTooltipText {
            get {
                return ResourceManager.GetString("AddToWatchlistTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Aspallar.
        /// </summary>
        public static string AppByLineText {
            get {
                return ResourceManager.GetString("AppByLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki-Up.
        /// </summary>
        public static string AppNameText {
            get {
                return ResourceManager.GetString("AppNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May be caused by trying to upload from an unsupported video website.
        /// </summary>
        public static string BadVideoUploadRequest {
            get {
                return ResourceManager.GetString("BadVideoUploadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Blue.
        /// </summary>
        public static string BlueLightText {
            get {
                return ResourceManager.GetString("BlueLightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string ButtonAddCategoryText {
            get {
                return ResourceManager.GetString("ButtonAddCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string ButtonAddFilesText {
            get {
                return ResourceManager.GetString("ButtonAddFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to the upload list (Ctrl+A).
        /// </summary>
        public static string ButtonAddFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonAddFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string ButtonAddFolderText {
            get {
                return ResourceManager.GetString("ButtonAddFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add all files in a folder and sub-folders to the upload list..
        /// </summary>
        public static string ButtonAddFolderTooltipText {
            get {
                return ResourceManager.GetString("ButtonAddFolderTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        public static string ButtonAddTemplateText {
            get {
                return ResourceManager.GetString("ButtonAddTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAddText {
            get {
                return ResourceManager.GetString("ButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ButtonFindText {
            get {
                return ResourceManager.GetString("ButtonFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load content from file..
        /// </summary>
        public static string ButtonLoadContentTooltipText {
            get {
                return ResourceManager.GetString("ButtonLoadContentTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files from a previously saved upload list..
        /// </summary>
        public static string ButtonLoadFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonLoadFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string ButtonLoadText {
            get {
                return ResourceManager.GetString("ButtonLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNextText {
            get {
                return ResourceManager.GetString("ButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNoText {
            get {
                return ResourceManager.GetString("ButtonNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOkText {
            get {
                return ResourceManager.GetString("ButtonOkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ButtonPreviousText {
            get {
                return ResourceManager.GetString("ButtonPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Files.
        /// </summary>
        public static string ButtonRemoveFilesText {
            get {
                return ResourceManager.GetString("ButtonRemoveFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected files from the upload list..
        /// </summary>
        public static string ButtonRemoveFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonRemoveFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save content to file..
        /// </summary>
        public static string ButtonSaveContentTooltipText {
            get {
                return ResourceManager.GetString("ButtonSaveContentTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the upload list..
        /// </summary>
        public static string ButtonSaveFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonSaveFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Upload.
        /// </summary>
        public static string ButtonStopUploadText {
            get {
                return ResourceManager.GetString("ButtonStopUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel running upload..
        /// </summary>
        public static string ButtonStopUploadTooltipText {
            get {
                return ResourceManager.GetString("ButtonStopUploadTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ButtonUploadText {
            get {
                return ResourceManager.GetString("ButtonUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start uploading files. (Ctrl+U).
        /// </summary>
        public static string ButtonUploadTooltipText {
            get {
                return ResourceManager.GetString("ButtonUploadTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYesText {
            get {
                return ResourceManager.GetString("ButtonYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read content..
        /// </summary>
        public static string CantReadContentMessage {
            get {
                return ResourceManager.GetString("CantReadContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read upload list..
        /// </summary>
        public static string CantReadUploadListMessage {
            get {
                return ResourceManager.GetString("CantReadUploadListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save content..
        /// </summary>
        public static string CantSaveContentMessage {
            get {
                return ResourceManager.GetString("CantSaveContentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save upload list..
        /// </summary>
        public static string CantSaveUploadListMessage {
            get {
                return ResourceManager.GetString("CantSaveUploadListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[Category:{0}]].
        /// </summary>
        public static string CategoryTemplate {
            get {
                return ResourceManager.GetString("CategoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string CheckNowText {
            get {
                return ResourceManager.GetString("CheckNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        public static string ColorThemeText {
            get {
                return ResourceManager.GetString("ColorThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the wikitext to use as the initial page content for new images below. This will be only used for new images, it will not replace any existing page content..
        /// </summary>
        public static string ContentDescriptionText {
            get {
                return ResourceManager.GetString("ContentDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentLabelText {
            get {
                return ResourceManager.GetString("ContentLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentTabText {
            get {
                return ResourceManager.GetString("ContentTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string ContiuePrompt {
            get {
                return ResourceManager.GetString("ContiuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not remember password.
        /// </summary>
        public static string DoNotRememberPassword {
            get {
                return ResourceManager.GetString("DoNotRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string DownloadNowText {
            get {
                return ResourceManager.GetString("DownloadNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter file extension.
        /// </summary>
        public static string EnterFileExtension {
            get {
                return ResourceManager.GetString("EnterFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitleText {
            get {
                return ResourceManager.GetString("ErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Files.
        /// </summary>
        public static string FilesText {
            get {
                return ResourceManager.GetString("FilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Uploading File.
        /// </summary>
        public static string FollowUploadFileHeader {
            get {
                return ResourceManager.GetString("FollowUploadFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scroll to the uploading file when it starts uploading..
        /// </summary>
        public static string FollowUploadFileText {
            get {
                return ResourceManager.GetString("FollowUploadFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French translation by.
        /// </summary>
        public static string FrenchTrsnslationText {
            get {
                return ResourceManager.GetString("FrenchTrsnslationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German translation by.
        /// </summary>
        public static string GermanTrsnslationText {
            get {
                return ResourceManager.GetString("GermanTrsnslationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Forest.
        /// </summary>
        public static string GreenForestText {
            get {
                return ResourceManager.GetString("GreenForestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore warnings.
        /// </summary>
        public static string IgnoreWarningsLabelText {
            get {
                return ResourceManager.GetString("IgnoreWarningsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore warnings and upload files even if they already exist or are duplicates..
        /// </summary>
        public static string IgnoreWarningsTooltipText {
            get {
                return ResourceManager.GetString("IgnoreWarningsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a list of file extensions that Wiki-Up will consider to be image files in the add files dialog..
        /// </summary>
        public static string ImageFilesDetailsText {
            get {
                return ResourceManager.GetString("ImageFilesDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File Extensions.
        /// </summary>
        public static string ImageFilesText {
            get {
                return ResourceManager.GetString("ImageFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string IncludeAllFiles {
            get {
                return ResourceManager.GetString("IncludeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include files of type.
        /// </summary>
        public static string IncludeFilesOfType {
            get {
                return ResourceManager.GetString("IncludeFilesOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All image files.
        /// </summary>
        public static string IncludeImageFiles {
            get {
                return ResourceManager.GetString("IncludeImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include sub-folders.
        /// </summary>
        public static string IncludeSubfolders {
            get {
                return ResourceManager.GetString("IncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All uploadable files.
        /// </summary>
        public static string IncludeUploadableFiles {
            get {
                return ResourceManager.GetString("IncludeUploadableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http connections are not secure. Signing in using http will result in your user name and password being sent in unencrypted plain text..
        /// </summary>
        public static string InsecureConnectionMessage {
            get {
                return ResourceManager.GetString("InsecureConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure Connection.
        /// </summary>
        public static string InsecureConnectionTitleText {
            get {
                return ResourceManager.GetString("InsecureConnectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid extension.
        /// </summary>
        public static string InvalidExtension {
            get {
                return ResourceManager.GetString("InvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the above details are correct..
        /// </summary>
        public static string InvalidLoginDetailsMessage {
            get {
                return ResourceManager.GetString("InvalidLoginDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wiki url..
        /// </summary>
        public static string LoginErrorInvalidWikiUrl {
            get {
                return ResourceManager.GetString("LoginErrorInvalidWikiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a wiki url and username..
        /// </summary>
        public static string LoginErrorNoWikiOrUsername {
            get {
                return ResourceManager.GetString("LoginErrorNoWikiOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server aborted the login (you may need to use a BOT password).
        /// </summary>
        public static string LoginExceptionAborted {
            get {
                return ResourceManager.GetString("LoginExceptionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid response..
        /// </summary>
        public static string LoginExceptionInvalidResponse {
            get {
                return ResourceManager.GetString("LoginExceptionInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain edit token..
        /// </summary>
        public static string LoginExceptionNoEditToken {
            get {
                return ResourceManager.GetString("LoginExceptionNoEditToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to use Wiki-Up on this wiki..
        /// </summary>
        public static string LoginExceptionNotAuthorized {
            get {
                return ResourceManager.GetString("LoginExceptionNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That account is not autoconfirmed..
        /// </summary>
        public static string LoginExceptionNotAutoConfirmed {
            get {
                return ResourceManager.GetString("LoginExceptionNotAutoConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not respond..
        /// </summary>
        public static string LoginExceptionTimeout {
            get {
                return ResourceManager.GetString("LoginExceptionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string LoginExceptionUnexpectedError {
            get {
                return ResourceManager.GetString("LoginExceptionUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to login again to continue with the upload, click on OK to log in..
        /// </summary>
        public static string LoginExpiredSubtext {
            get {
                return ResourceManager.GetString("LoginExpiredSubtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login credentials have expired..
        /// </summary>
        public static string LoginExpiredText {
            get {
                return ResourceManager.GetString("LoginExpiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize/Restore.
        /// </summary>
        public static string ManimizeRestoreText {
            get {
                return ResourceManager.GetString("ManimizeRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midnight Lights.
        /// </summary>
        public static string MidnightLightsText {
            get {
                return ResourceManager.GetString("MidnightLightsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MiximizeText {
            get {
                return ResourceManager.GetString("MiximizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New image extension..
        /// </summary>
        public static string NewImageExtension {
            get {
                return ResourceManager.GetString("NewImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of Wiki-Up, version {0}, is available for download..
        /// </summary>
        public static string NewVersionMessage {
            get {
                return ResourceManager.GetString("NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version Available.
        /// </summary>
        public static string NewVersionTitleText {
            get {
                return ResourceManager.GetString("NewVersionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki does not support video uploading.
        /// </summary>
        public static string NoVideoUploadSupport {
            get {
                return ResourceManager.GetString("NoVideoUploadSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length is {0} videos..
        /// </summary>
        public static string PlalistMaximumLength {
            get {
                return ResourceManager.GetString("PlalistMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist is too large to import..
        /// </summary>
        public static string PlalistTooBig {
            get {
                return ResourceManager.GetString("PlalistTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Haze.
        /// </summary>
        public static string PutpleHazeText {
            get {
                return ResourceManager.GetString("PutpleHazeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple Overload.
        /// </summary>
        public static string PutpleOverloadText {
            get {
                return ResourceManager.GetString("PutpleOverloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rakdos.
        /// </summary>
        public static string RakdosText {
            get {
                return ResourceManager.GetString("RakdosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password for domain.
        /// </summary>
        public static string RememberPasswordForDomain {
            get {
                return ResourceManager.GetString("RememberPasswordForDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password for wiki.
        /// </summary>
        public static string RememberPasswordForWiki {
            get {
                return ResourceManager.GetString("RememberPasswordForWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extension.
        /// </summary>
        public static string RemoveExtension {
            get {
                return ResourceManager.GetString("RemoveExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        public static string RestoreDefaultsText {
            get {
                return ResourceManager.GetString("RestoreDefaultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string SaveSettingsText {
            get {
                return ResourceManager.GetString("SaveSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while probing the wiki..
        /// </summary>
        public static string SearchErrorText {
            get {
                return ResourceManager.GetString("SearchErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort of Solarized.
        /// </summary>
        public static string SolarizedText {
            get {
                return ResourceManager.GetString("SolarizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the summary for the upload in the wiki&apos;s activity log..
        /// </summary>
        public static string SummaryDescriptionText {
            get {
                return ResourceManager.GetString("SummaryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryLabelText {
            get {
                return ResourceManager.GetString("SummaryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the Language and Color Theme settings will take effect the next time Wiki-Up is run..
        /// </summary>
        public static string TakeEffectNextRunText {
            get {
                return ResourceManager.GetString("TakeEffectNextRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string ToggleSwitchNoText {
            get {
                return ResourceManager.GetString("ToggleSwitchNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string ToggleSwitchYesText {
            get {
                return ResourceManager.GetString("ToggleSwitchYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add files..
        /// </summary>
        public static string UnableToAddFiles {
            get {
                return ResourceManager.GetString("UnableToAddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new versions of Wiki-Up when Wiki-Up starts up..
        /// </summary>
        public static string UpdatesDetailsText {
            get {
                return ResourceManager.GetString("UpdatesDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string UpdatesText {
            get {
                return ResourceManager.GetString("UpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the time, in milliseconds, that Wiki-Up waits between each file upload..
        /// </summary>
        public static string UploadDelayDetailsText {
            get {
                return ResourceManager.GetString("UploadDelayDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Delay.
        /// </summary>
        public static string UploadDelayText {
            get {
                return ResourceManager.GetString("UploadDelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists.
        /// </summary>
        public static string UploadErrorAlreadyExists {
            get {
                return ResourceManager.GetString("UploadErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file name.
        /// </summary>
        public static string UploadErrorBadFilename {
            get {
                return ResourceManager.GetString("UploadErrorBadFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted File.
        /// </summary>
        public static string UploadErrorDeletedFile {
            get {
                return ResourceManager.GetString("UploadErrorDeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate of archived.
        /// </summary>
        public static string UploadErrorDuplicateArchive {
            get {
                return ResourceManager.GetString("UploadErrorDuplicateArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is empty.
        /// </summary>
        public static string UploadErrorEmptyFile {
            get {
                return ResourceManager.GetString("UploadErrorEmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large file warning.
        /// </summary>
        public static string UploadErrorLargeFile {
            get {
                return ResourceManager.GetString("UploadErrorLargeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwanted file type.
        /// </summary>
        public static string UploadErrorUnwantedType {
            get {
                return ResourceManager.GetString("UploadErrorUnwantedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD LIST.
        /// </summary>
        public static string UploadListWatermarkText {
            get {
                return ResourceManager.GetString("UploadListWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an invalid JSON response..
        /// </summary>
        public static string UploadMesageInvalidJson {
            get {
                return ResourceManager.GetString("UploadMesageInvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting upload..
        /// </summary>
        public static string UploadMessageAwaitingUpload {
            get {
                return ResourceManager.GetString("UploadMessageAwaitingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload canceled..
        /// </summary>
        public static string UploadMessageCancelled {
            get {
                return ResourceManager.GetString("UploadMessageCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string UploadMessageFileNotFound {
            get {
                return ResourceManager.GetString("UploadMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files of type &quot;{0}&quot; are not permitted..
        /// </summary>
        public static string UploadMessageFileTypeNotPermitted {
            get {
                return ResourceManager.GetString("UploadMessageFileTypeNotPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server returned an invalid XML response..
        /// </summary>
        public static string UploadMessageInvalidXml {
            get {
                return ResourceManager.GetString("UploadMessageInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error. Unable to upload..
        /// </summary>
        public static string UploadMessageNetworkError {
            get {
                return ResourceManager.GetString("UploadMessageNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain valid edit token. Uploads canceled. You may have to restart Wiki-Up to resolve this error..
        /// </summary>
        public static string UploadMessageNoEditToken {
            get {
                return ResourceManager.GetString("UploadMessageNoEditToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read file..
        /// </summary>
        public static string UploadMessageReadFail {
            get {
                return ResourceManager.GetString("UploadMessageReadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is too busy. Uploads canceled. Try again later..
        /// </summary>
        public static string UploadMessageServerBusy {
            get {
                return ResourceManager.GetString("UploadMessageServerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload timed out..
        /// </summary>
        public static string UploadMessageTimedOut {
            get {
                return ResourceManager.GetString("UploadMessageTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected server response..
        /// </summary>
        public static string UploadMessageUnkownServerResponse {
            get {
                return ResourceManager.GetString("UploadMessageUnkownServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading to wiki....
        /// </summary>
        public static string UploadMessageUploading {
            get {
                return ResourceManager.GetString("UploadMessageUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate of.
        /// </summary>
        public static string UploadResponseDuplicateOf {
            get {
                return ResourceManager.GetString("UploadResponseDuplicateOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadTabText {
            get {
                return ResourceManager.GetString("UploadTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded via.
        /// </summary>
        public static string UploadViaText {
            get {
                return ResourceManager.GetString("UploadViaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki-Up is up to date..
        /// </summary>
        public static string UpToDateText {
            get {
                return ResourceManager.GetString("UpToDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via.
        /// </summary>
        public static string ViaText {
            get {
                return ResourceManager.GetString("ViaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to view image..
        /// </summary>
        public static string ViewImageErrorMessage {
            get {
                return ResourceManager.GetString("ViewImageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View list of uploaded files..
        /// </summary>
        public static string ViewUploadedFiles {
            get {
                return ResourceManager.GetString("ViewUploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting before trying again..
        /// </summary>
        public static string WaitingForRetry {
            get {
                return ResourceManager.GetString("WaitingForRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string WebsiteText {
            get {
                return ResourceManager.GetString("WebsiteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiki url.
        /// </summary>
        public static string WikiUrlPlaceholder {
            get {
                return ResourceManager.GetString("WikiUrlPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while communicating with Youtube..
        /// </summary>
        public static string YoutubeError {
            get {
                return ResourceManager.GetString("YoutubeError", resourceCulture);
            }
        }
    }
}
