//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiUpload.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WikiUpload.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string AboutMenuItemText {
            get {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to watch list.
        /// </summary>
        public static string AddToWatchlistLabelText {
            get {
                return ResourceManager.GetString("AddToWatchlistLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the uploaded files to your watch list..
        /// </summary>
        public static string AddToWatchlistTooltipText {
            get {
                return ResourceManager.GetString("AddToWatchlistTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Aspallar.
        /// </summary>
        public static string AppByLineText {
            get {
                return ResourceManager.GetString("AppByLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki-Up.
        /// </summary>
        public static string AppNameText {
            get {
                return ResourceManager.GetString("AppNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string ButtonAddCategoryText {
            get {
                return ResourceManager.GetString("ButtonAddCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string ButtonAddFilesText {
            get {
                return ResourceManager.GetString("ButtonAddFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to the upload list (Ctrl+A).
        /// </summary>
        public static string ButtonAddFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonAddFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template.
        /// </summary>
        public static string ButtonAddTemplateText {
            get {
                return ResourceManager.GetString("ButtonAddTemplateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ButtonAddText {
            get {
                return ResourceManager.GetString("ButtonAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelText {
            get {
                return ResourceManager.GetString("ButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string ButtonFindText {
            get {
                return ResourceManager.GetString("ButtonFindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load content from file..
        /// </summary>
        public static string ButtonLoadContentTooltipText {
            get {
                return ResourceManager.GetString("ButtonLoadContentTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files from a previously saved upload list..
        /// </summary>
        public static string ButtonLoadFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonLoadFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string ButtonLoadText {
            get {
                return ResourceManager.GetString("ButtonLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNextText {
            get {
                return ResourceManager.GetString("ButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ButtonNoText {
            get {
                return ResourceManager.GetString("ButtonNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ButtonPreviousText {
            get {
                return ResourceManager.GetString("ButtonPreviousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Files.
        /// </summary>
        public static string ButtonRemoveFilesText {
            get {
                return ResourceManager.GetString("ButtonRemoveFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected files from the upload list..
        /// </summary>
        public static string ButtonRemoveFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonRemoveFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save content to file..
        /// </summary>
        public static string ButtonSaveContentTooltipText {
            get {
                return ResourceManager.GetString("ButtonSaveContentTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the upload list..
        /// </summary>
        public static string ButtonSaveFilesTooltipText {
            get {
                return ResourceManager.GetString("ButtonSaveFilesTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSaveText {
            get {
                return ResourceManager.GetString("ButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Upload.
        /// </summary>
        public static string ButtonStopUploadText {
            get {
                return ResourceManager.GetString("ButtonStopUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel running upload..
        /// </summary>
        public static string ButtonStopUploadTooltipText {
            get {
                return ResourceManager.GetString("ButtonStopUploadTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string ButtonUploadText {
            get {
                return ResourceManager.GetString("ButtonUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start uploading files. (Ctrl+U).
        /// </summary>
        public static string ButtonUploadTooltipText {
            get {
                return ResourceManager.GetString("ButtonUploadTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ButtonYesText {
            get {
                return ResourceManager.GetString("ButtonYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the wikitext to use as the initial page content for new images below. This will be only used for new images, it will not replace any existing page content..
        /// </summary>
        public static string ContentDescriptionText {
            get {
                return ResourceManager.GetString("ContentDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentLabelText {
            get {
                return ResourceManager.GetString("ContentLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string ContentTabText {
            get {
                return ResourceManager.GetString("ContentTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string ContiuePrompt {
            get {
                return ResourceManager.GetString("ContiuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Files.
        /// </summary>
        public static string FilesText {
            get {
                return ResourceManager.GetString("FilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore warnings.
        /// </summary>
        public static string IgnoreWarningsLabelText {
            get {
                return ResourceManager.GetString("IgnoreWarningsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore warnings and upload files even if they already exist or are duplicates..
        /// </summary>
        public static string IgnoreWarningsTooltipText {
            get {
                return ResourceManager.GetString("IgnoreWarningsTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http connections are not secure. Signing in using http will result in your user name and password being sent in unencrypted plain text..
        /// </summary>
        public static string InsecureConnectionMessage {
            get {
                return ResourceManager.GetString("InsecureConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecure Connection.
        /// </summary>
        public static string InsecureConnectionTitleText {
            get {
                return ResourceManager.GetString("InsecureConnectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the above details are correct..
        /// </summary>
        public static string InvalidLoginDetailsMessage {
            get {
                return ResourceManager.GetString("InvalidLoginDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wiki url..
        /// </summary>
        public static string LoginErrorInvalidWikiUrl {
            get {
                return ResourceManager.GetString("LoginErrorInvalidWikiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a wiki url and username..
        /// </summary>
        public static string LoginErrorNoWikiOrUsername {
            get {
                return ResourceManager.GetString("LoginErrorNoWikiOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailedMessage {
            get {
                return ResourceManager.GetString("LoginFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize/Restore.
        /// </summary>
        public static string ManimizeRestoreText {
            get {
                return ResourceManager.GetString("ManimizeRestoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MiximizeText {
            get {
                return ResourceManager.GetString("MiximizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Password.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while probing the wiki..
        /// </summary>
        public static string SearchErrorText {
            get {
                return ResourceManager.GetString("SearchErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the summary for the upload in the wiki&apos;s activity log..
        /// </summary>
        public static string SummaryDescriptionText {
            get {
                return ResourceManager.GetString("SummaryDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SummaryLabelText {
            get {
                return ResourceManager.GetString("SummaryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string ToggleSwitchNoText {
            get {
                return ResourceManager.GetString("ToggleSwitchNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string ToggleSwitchYesText {
            get {
                return ResourceManager.GetString("ToggleSwitchYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadTabText {
            get {
                return ResourceManager.GetString("UploadTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UsernamePlaceholder {
            get {
                return ResourceManager.GetString("UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wiki url.
        /// </summary>
        public static string WikiUrlPlaceholder {
            get {
                return ResourceManager.GetString("WikiUrlPlaceholder", resourceCulture);
            }
        }
    }
}
